ProjektPZ/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace ProjektPZ.Models
{
    public class Persona
    {
        public int ID { get; set; }

        [StringLength(50, ErrorMessage = "Imie nie może być dłuższe niż 50 znaków!")]
        [Required(ErrorMessage = "Imie jest wymagane")]
        public string FirstName { get; set; }

        [StringLength(50, ErrorMessage = "Nazwisko nie może być dłuższe niż 50 znaków!")]
        [Required(ErrorMessage = "Nazwisko jest wymagane")]
        public string LastName { get; set; }
        [StringLength(200, ErrorMessage = "Miejsce urodzenia nie może być dłuższe niż 200 znaków")]
        [Required(ErrorMessage = "Miejsce urodzenia jest wymaganee")]
        public string PlaceOfBirth { get; set; }

        [DataType(DataType.Date)]
       // [DisplayFormat(DataFormatString = "{d:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime BirthDate { get; set; }
        public string Image { get; set; }

        //public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<Biography> Biographys { get; set; }
        public virtual ICollection<FilmHasPersonas> ListOfFilms { get; set; }
       

        public Persona()
        {
            ListOfFilms = new List<FilmHasPersonas>();
            Awards = new List<Award>();
            Biographys = new List<Biography>();
            //Comments = new List<Comment>();
            
        }
    }
}

ProjektPZ/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjektPZ.DAL;
using ProjektPZ.Models;
using PagedList;

namespace ProjektPZ.Controllers
{
    public class PersonasController : Controller
    {
        private ProjectDb db = new ProjectDb();

        // GET: Personas
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.NameSortPackParam = String.IsNullOrEmpty(sortOrder) ? "firstName_desc" : "";
            ViewBag.LastNamePackParam = sortOrder == "lastName" ? "lastName_desc" : "lastName";

            if (searchString != null)
            {
                page = 1;
            }else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var personas = from p in db.Personas select p;

            if (! String.IsNullOrEmpty(searchString))
            {
                personas = personas.Where(x => x.LastName.Contains(searchString) || x.FirstName.Contains(searchString));
            }

            switch(sortOrder)
            {
                case "firstName_desc":
                    {
                        personas = personas.OrderByDescending(x => x.FirstName);
                        break;
                    }
                case "lastName":
                    {
                        personas = personas.OrderBy(x => x.LastName);
                        break;
                    }
                case "lastName_desc":
                    {
                        personas = personas.OrderByDescending(x => x.LastName);
                        break;
                    }
                default:
                    {
                        personas = personas.OrderBy(x => x.FirstName);
                        break;
                    }
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View( personas.ToPagedList(pageNumber, pageSize));
        }

        // GET: Personas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Persona persona = db.Personas.Find(id);

            if (persona == null)
            {
               return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            List<Film> listOfFilms = new List<Film>();

            foreach (FilmHasPersonas f in persona.ListOfFilms)
                listOfFilms.Add(db.ListOfFilms.Find(f.Film.ID));

            PersonaAll p = new PersonaAll() { Persona = persona, ListOfFilms = listOfFilms };

            return View(p);
        }

        // GET: Personas/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create( Persona persona)
        {
            HttpPostedFileBase file = Request.Files["Image"];

            if (ModelState.IsValid)
            {
                db.Personas.Add(persona);
                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/") + "p_" + persona.ID + ".jpg");
                }

                return RedirectToAction("Details", new { persona.ID});
            }

            return View(persona);
        }



        // GET: Personas/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Persona persona)
        {
            HttpPostedFileBase file = Request.Files["Image"];
            int id = Convert.ToInt32(TempData["ID"]);

            if (ModelState.IsValid)
            {
                Persona p = db.Personas.Find(id);
                p.FirstName = persona.FirstName;
                p.LastName = persona.LastName;
                p.PlaceOfBirth = persona.PlaceOfBirth;
                p.BirthDate = persona.BirthDate;
                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/") + "p_" + id + ".jpg");
                }

                return Redirect("/Personas/Details/" + id);
            }
            return View(persona);
        }
       
       
        // GET: Personas/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Persona persona = db.Personas.Find(id);
            List<Biography> b =(List<Biography>) persona.Biographys;
            List<FilmHasPersonas> f = (List<FilmHasPersonas>)persona.ListOfFilms;
            List<Award> a = (List<Award>)persona.Awards;

            foreach (Biography i in b.ToList())
            {
                db.Biographies.Remove(i);
            }
            foreach (FilmHasPersonas i in f.ToList())
            {
                db.FilmPersonas.Remove(i);
            }
            foreach (Award i in a.ToList())
            {
                db.Awards.Remove(i);
            }
            
            db.Personas.Remove(persona);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjektPZ/Views/Personas/Create.cshtml
@model ProjektPZ.Models.Persona

@{
    ViewBag.Title = "Dodaj osobę";
}

<h2>Dodaj osobę</h2>


@using (Html.BeginForm("Create", "Personas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Imie
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            Nazwisko
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Miejsce urodzenia
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Data urodzenia
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Dodaj zdjęcie osoby
            <div class="col-md-10">
                <input type="file" name="Image" />
                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjektPZ/Views/Personas/Delete.cshtml
@model ProjektPZ.Models.Persona

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjektPZ/Views/Personas/Details.cshtml
@model ProjektPZ.Models.PersonaAll
@{
    ViewBag.Title = "Szczegóły";
    TempData["IDP"] = Model.Persona.ID;
}

<br />
<div class="bg-dark text-white">
    <table>
        <tr>
            <td>
                <img src="~/Images/p_@(Model.Persona.ID).jpg" alt="@Model.Persona.FirstName @Model.Persona.LastName" />
            </td>
            <td></td>
            <td>
                <h2>
                    @Model.Persona.FirstName
                    @Model.Persona.LastName
                </h2>
                <p>data urodzenia: @Model.Persona.BirthDate.ToShortDateString()</p>
                <p>miejsce urodzenia: @Model.Persona.PlaceOfBirth;</p>
            </td>
        </tr>
    </table>
    

      
    <br /><br />

    @if (Request.IsAuthenticated)
    {
       <p> <a href="/Biographies/Create/@(Model.Persona.ID)">Dodaj biografię</a></p>
    }
    <table class="table" style="width:70%">
        @foreach (var i in Model.Persona.Biographys)
        {
            <tr>
                <td scope="row" style="width:80%">
                    <p><b>Biografia użytkownika @i.User.UserName.Split('@')[0]</b></p>
                    <div>
                        @if (i.Content.Count() > 200)
                        {
                            @i.Content.Substring(0, 200);
                            <a href="/Biographies/Details/@i.ID">Zobacz całą biografię</a>
                        }
                        else
                        {
                            @i.Content
                        }
                    </div>
                </td>
                <td scope="row">
                    @if (Request.IsAuthenticated && User.Identity.Name.Equals(i.User.UserName))
                    {
                        <a href="/Biographies/Edit/@i.ID"> | Edytuj</a>
                        <a href="/Biographies/Delete/@i.ID"> | Usuń</a>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <a href="/Biographies/Delete/@i.ID"> | Usuń</a>
                    }

                </td>
            </tr>

        }
    </table>
        <br />
        <br />
        <h3>Nagrody</h3>

        <table class="table" style="width: 50%">
            <tr>
                <th scope="col">Rok otrzymania</th>
                <th scope="col">Nazwa nagrody</th>
                <th scope="col">Kategoria</th>
                <th scope="col">Film</th>
            </tr>

            @foreach (var i in Model.Persona.Awards.OrderByDescending(x => x.YearOfWining))
            {

                <tr>
                    <td scope="row">
                        @i.YearOfWining
                    </td>
                    <td>
                        @i.Name
                    </td>
                    <td>
                        @i.ForWhat
                    </td>
                    <td>
                        <a href="/Films/Details/@i.Film.ID">
                            @if (i.Film.OrgTitle.Equals(i.Film.Title))
                            {
                                @i.Film.Title
                            }
                            else
                            {
                                @i.Film.Title <br />
                                @i.Film.OrgTitle
                            }
                        </a>
                    </td>


                </tr>
            }

        </table>
        @if (Request.IsAuthenticated)
        {
            <a href="/Awards/CreatePAward/?idp=@Model.Persona.ID">Dodaj nagrodę</a>

        }


        <br />
        <br />



        <h3>Filmografia</h3>

        <table class="table" style="width: 50%">
            <tr>
                <th scope="col">Rok premiery</th>
                <th scope="col">Tytuł fimlu</th>
                <th scope="col">Rola w filmie</th>
            </tr>

            @foreach (var i in Model.Persona.ListOfFilms.OrderByDescending(x => x.Film.YearOfPremiere))
            {

                <tr>
                    <td scope="row">
                        @i.Film.YearOfPremiere
                    </td>
                    <td>
                        <a href="/Films/Details/@i.Film.ID">@i.Film.Title</a>
                    </td>
                    <td>
                        @i.Function
                    </td>

                </tr>

            }

        </table>

        @if (Request.IsAuthenticated)
        {
            <a href="/FilmHasPersonas/CreateP/?idp=@Model.Persona.ID">Dodaj film</a>

        }

    <br /><br />
</div>
<p>
    @if (Request.IsAuthenticated)
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.Persona.ID })
    }
    
    @Html.ActionLink("Powrót do listy", "Index")
</p>

ProjektPZ/Views/Personas/Edit.cshtml
@model ProjektPZ.Models.Persona

@{
    ViewBag.Title = "Edytuj osobę";
    TempData["ID"] = Model.ID;
}

<h2>Edytuj osobę</h2>


@using (Html.BeginForm("Edit", "Personas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Imie
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Nazwisko
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Miejsce urodzenia
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Data urodzenia
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            Dodaj zdjęcie osoby
            <div class="col-md-10">
                <input type="file" name="Image" />

            </div>
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edytuj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjektPZ/Views/Personas/Index.cshtml
@model PagedList.IPagedList<ProjektPZ.Models.Persona>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Lista ludzi kina";
}

<h2>Lista ludzi kina</h2>

<p>
    @if (Request.IsAuthenticated)
    {
        <h4>@Html.ActionLink("Dodaj nową osobistość", "Create")</h4>
    }
    
</p>

@using (Html.BeginForm())
{
    <p>
        Wyszukaj osobę: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Wyszukaj" />
    </p>
}

<table class="table" style="width: 50%" >
    <tr>
        <th></th>
        <th>
            @Html.ActionLink("Sortuj po imieniu", "Index", new { sortOrder = ViewBag.NameSortPackParam, currentFilter = ViewBag.CurrentFilter })
         </th>
         <th>  
             @Html.ActionLink("Sortuj po nazwisku", "Index", new { sortOrder = ViewBag.LastNamePackParam , currentFilter = ViewBag.CurrentFilter})

        </th>
    </tr>

@foreach (var item in Model)
{
    <tr onclick="location.href = '@(Url.Action("Details", "Personas", new { id = item.ID }))'">

        <td>
            <img src="~/Images/p_@(item.ID).jpg"  style="width:100px;height:120px;" href="/Personas/Details/@item.ID"  class="img-fluid " />
        </td>
        <td>
            <a href="/Personas/Details/@item.ID">
                <h3>@Html.DisplayFor(modelItem => item.FirstName)</h3>
                <h3>@Html.DisplayFor(modelItem => item.LastName)</h3>
            </a>
        </td>
        <td>
            @if (Request.IsAuthenticated)
            {
                @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) <br/>
                
            }
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Usuń", "Delete", new { id = item.ID })
            }

        </td>
    </tr>
}
    @if (Model.Count == 0)
    {
        <tr><td>Nie ma osoby</td></tr>
    }
</table>
<br />
Strona @(Model.PageCount<Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))