ProjektPZ/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ProjektPZ.ViewModels;

namespace ProjektPZ.Models
{
    public class Film
    {
        public int ID { get; set; }


        [StringLength(100, ErrorMessage = "Tytuł nie może być dłuższy niż 100 znaków!")]
        public string Title { get; set; }

        [StringLength(100, ErrorMessage ="Tytuł nie może być dłuższy niż 100 znaków!")]
        [Required(ErrorMessage = "Oryginalny tytuł jest wymagany")]
        public string OrgTitle { get; set; }
        
        [Required(ErrorMessage = "Rok premiery jest wymagany")]
        public int YearOfPremiere { get; set; }

        [StringLength(500, ErrorMessage = "Opis nie może być dłuższy niż 500 znaków!")]
        [Required(ErrorMessage = "Opis jest wymagany")]
        public string Description { get; set; }

        public virtual ICollection<Rating> Ratings { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual ICollection<Award> ListOfAwards { get; set; }

        [Required(ErrorMessage = "Dodaj co najmniej jedną osobistość")]
        public virtual ICollection<FilmHasPersonas> ListOfPersonas { get; set; }

        public virtual  ICollection<Review> ListOfReviews { get; set; }
        //public virtual  ICollection<Comment> ListOfComments { get; set; }

        public Film()
        {
            ListOfAwards = new List<Award>();
            //ListOfComments = new List<Comment>();
            ListOfReviews = new List<Review>();
            ListOfPersonas = new List<FilmHasPersonas>();

        }
    }
}

ProjektPZ/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjektPZ.DAL;
using ProjektPZ.Models;
using PagedList;
using System.Globalization;

namespace ProjektPZ.Controllers
{
    public class FilmsController : Controller
    {
        private ProjectDb db = new ProjectDb();

        // GET: ListOfFilms

        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page, int? genre)
        {
            ViewBag.NameSortPackParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DatePackParam = sortOrder == "date" ? "date_desc" : "date";

            if (genre == null)
                genre = -1;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var films = from p in db.ListOfFilms select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                if (genre != -1)
                {
                    films = films.Where(x => (x.Title.Contains(searchString) || x.OrgTitle.Contains(searchString)) && (x.Genre.ID == genre));
                }else
                    films = films.Where(x => x.Title.Contains(searchString) || x.OrgTitle.Contains(searchString));

            }else
            {
                if (genre != -1)
                    films = films.Where(x => x.Genre.ID == genre);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    {
                        films = films.OrderByDescending(x => x.Title);
                        break;
                    }
                case "date":
                    {
                        films = films.OrderBy(x => x.YearOfPremiere);
                        break;
                    }
                case "date_desc":
                    {
                        films = films.OrderByDescending(x => x.YearOfPremiere);
                        break;
                    }
                default:
                    {
                        films = films.OrderBy(x => x.Title);
                        break;
                    }
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(films.ToPagedList(pageNumber, pageSize));
        }

        // GET: ListOfFilms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.ListOfFilms.Find(id);

            bool fav = db.Favorites.Where(x => x.Film.ID == film.ID && x.User.UserName.Equals(User.Identity.Name)).Any();
            if (fav)
            {
                ViewBag.ID = db.Favorites.Where(x => x.Film.ID == film.ID && x.User.UserName.Equals(User.Identity.Name)).Single().ID;
            }
            else
                ViewBag.ID = -1;

            if (film == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            List<Persona> listOfPersonas = new List<Persona>();

            foreach (FilmHasPersonas f in film.ListOfPersonas)
            {
                listOfPersonas.Add(f.Persona);
            }


            PersonaAll p = new PersonaAll() { ListOfPersona = listOfPersonas, Film = film };

            return View(p);
        }

        // GET: ListOfFilms/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }



        // POST: ListOfFilms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ID,Title,OrgTitle,YearOfPremiere,Description,ListOfGenres,ListOfAwards,ListOfPersonas")] Film film)
        {
            HttpPostedFileBase file = Request.Files["Image"];
            int id = Convert.ToInt32(TempData["ID"]);

            if (ModelState.IsValid)
            {
                db.ListOfFilms.Add(film);
                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/") + "f_" + id + ".jpg");
                }

                return Redirect("/Films/Details/" + id);
            }

            return View(film);
        }

        // GET: ListOfFilms/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.ListOfFilms.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: ListOfFilms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Film film)
        {
            HttpPostedFileBase file = Request.Files["Image"];
            int id = Convert.ToInt32(TempData["ID"]);

            if (ModelState.IsValid)
            {
                Film f = db.ListOfFilms.Find(id);
                f.Description = film.Description;
                f.Title = film.Title;
                f.OrgTitle = film.OrgTitle;
                f.YearOfPremiere = film.YearOfPremiere;

                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/") + "f_" + id + ".jpg");
                }

                return Redirect("/Films/Details/" + id);
            }
            return View(film);
        }

        // GET: ListOfFilms/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.ListOfFilms.Find(id);

            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: ListOfFilms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = db.ListOfFilms.Find(id);
            List<Award> a = (List<Award>)film.ListOfAwards;
            List<Review> b = (List<Review>)film.ListOfReviews;
            List<FilmHasPersonas> c = (List<FilmHasPersonas>)film.ListOfPersonas;

            foreach (Award i in a.ToList())
            {
                db.Awards.Remove(i);
            }
            foreach (Review i in b.ToList())
            {
                db.Reviews.Remove(i);
            }
            foreach (FilmHasPersonas i in c.ToList())
            {
                db.Personas.Find(i.Persona.ID).ListOfFilms.Remove(i);
            }
            foreach (FilmHasPersonas i in c.ToList())
            {
                db.FilmPersonas.Remove(i);
            }
            db.ListOfFilms.Remove(film);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private Persona DefaultPersona(string firstName, string lastName)
        {
            return new Persona() { FirstName = firstName, LastName = lastName, BirthDate = DateTime.ParseExact("01/01/1900", "dd/MM/yyyy", CultureInfo.InvariantCulture), PlaceOfBirth = "?" };
        }

        [Authorize]
        public ActionResult AddRating(int id, int ranting)
        {
            Film f = db.ListOfFilms.Find(id);
            ApplicationUser user = db.Users.Where(x => x.UserName.Equals(User.Identity.Name)).Single();

            if (db.Ratings.Where(x => x.Film.ID == f.ID && x.User.Id == user.Id).Any())
            {
                db.Ratings.Where(x => x.Film.ID == f.ID && x.User.Id == user.Id).Single().Rate = ranting * 10;
            }else
            {
                Rating r = new Rating() { Film = f, Rate = (ranting * 10), User = user };
                db.Ratings.Add(r);
            }

           
            db.SaveChanges();

            return Redirect("/Films/Details/" + id);
        }

        [Authorize]
        public ActionResult RemoveFromFavorite(int id)
        {
            Favorite f = db.Favorites.Find(id);
            int i = f.Film.ID;
            db.Favorites.Remove(f);
            db.SaveChanges();

            return Redirect("/Films/Details/" + i);

        }
        [Authorize]
        public ActionResult AddToFavorite(int id)
        {
            Favorite f = new Favorite()
            {
                Film = db.ListOfFilms.Find(id),
                User = db.Users.Where(x => x.UserName.Equals(User.Identity.Name)).Single()
            };
            db.Favorites.Add(f);
            db.SaveChanges();
            
            return Redirect("/Films/Details/" + id);
        }
    }
}

ProjektPZ/Views/Films/Create.cshtml
@model ProjektPZ.Models.Film

@{
    ViewBag.Title = "Dodaj film";
}

<h2>Dodaj film</h2>


@using (Html.BeginForm("Create", "Films", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div >
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Tytuł filmu
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tytuł oryginalny
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrgTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrgTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Rok premiery
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfPremiere, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfPremiere, "", new { @class = "text-danger" })
            </div>
        </div>
            

            <div class="form-group">
                Opis filmu
                <div>
                    @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", @rows = 5, @cols = 60 })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                Dodaj plakat
                <div class="col-md-10">
                    <input type="file" name="Image" />

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Dodaj" class="btn btn-default" />
                </div>
            </div>
        </div>

}


<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjektPZ/Views/Films/Delete.cshtml
@model ProjektPZ.Models.Film

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearOfPremiere)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearOfPremiere)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjektPZ/Views/Films/Details.cshtml
@model ProjektPZ.Models.PersonaAll

@{
    ViewBag.Title = "Szczegóły";
    TempData["IDF"] = Model.Film.ID;
    
    int ocena = 0;
    int suma = 0;
    int liczbaGlosow = Model.Film.Ratings.Count();
    if (liczbaGlosow > 0)
    {
        foreach (var i in Model.Film.Ratings)
        {
            suma += i.Rate;
            if (i.User.UserName.Equals(User.Identity.Name))
            {
                ocena = i.Rate;
            }
        }
        suma /= liczbaGlosow;
    }
}


<div>
        <table>
            <tr>
                <td>
                    <img src="~/Images/f_@(Model.Film.ID).jpg" alt="@Model.Film.ID poster" />
                </td>
                <td >
                    <h2>
                        @Model.Film.Title
                    </h2>
                    @if (!Model.Film.Title.Equals(Model.Film.OrgTitle))
                    {
                        <h3>
                            @Model.Film.OrgTitle
                        </h3>
                    }
                    <p>
                        @Model.Film.Description
                    </p>
                    <p>
                        Rok premiery : @Model.Film.YearOfPremiere
                    </p>
                    <p>
                        Gatunek:

                        @Model.Film.Genre.Name
                    </p>

                </td>
            </tr>
        </table>
    
        @if (Request.IsAuthenticated && ViewBag.ID == -1)
        {
            <p> <a href="/Films/AddToFavorite/@Model.Film.ID">Dodaj do ulubionych</a></p>
        }    
        @if (Request.IsAuthenticated && ViewBag.ID != -1)
        {
            <p> <a href="/Films/RemoveFromFavorite/@ViewBag.ID">Usuń z ulubionych</a></p>
        }
        <p>
            <h4>Ocena: @(suma / 10.0) </h4> <h6>Głosy: @liczbaGlosow </h6>
        </p>

        @if (Request.IsAuthenticated)
        {
                <h3>Twoja ocena: @(ocena/10)</h3>

                <h3>Zagłosuj</h3>

                for (int i = 1; i <= 10; i++)
                {
                    <a href="/Films/AddRating/?id=@Model.Film.ID&ranting=@i">@i</a>
                }
        }
        else
        {
            <p>Zaloguj aby ocenić.</p>
        }
    
        <br />
        <br />


        @if (Request.IsAuthenticated)
        {
            <p> <a href="/Reviews/Create/@Model.Film.ID">Dodaj recenzje</a></p>
        }

        <table class="table" style="width:70%">
            @foreach (var i in Model.Film.ListOfReviews)
            {
                <tr>
                    <td scope="row" style="width:80%">
                        <p>Recenzja użytkownika @i.User.UserName.Split('@')[0]</p>
                        <div>
                            @if (i.Content.Count() > 200)
                            {
                                @i.Content.Substring(0, 200);
                                <a href="/Reviews/Details/@i.ID">Zobac całą recenzje</a>
                            }
                            else
                            {
                                @i.Content
                            }
                        </div>
                    </td>
                    <td scope="row">
                        @if (Request.IsAuthenticated && User.Identity.Name.Equals(i.User.UserName))
                        {
                            <a href="/Reviews/Edit/@i.ID"> | Edytuj</a>
                            <a href="/Reviews/Delete/@i.ID"> | Usuń</a>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <a href="/Reviews/Delete/@i.ID"> | Usuń</a>
                        }

                    </td>
                </tr>
            }

        </table>

        <br />
        <br />

        <h3>Nagrody</h3>

        <table class="table" style="width: 50%">
            <tr>
                <th scope="col">Rok otrzymania</th>
                <th scope="col">Nazwa nagrody</th>
                <th scope="col">Kategoria</th>
                <th scope="col">Osoba</th>
            </tr>

            @foreach (var i in Model.Film.ListOfAwards.OrderByDescending(x => x.YearOfWining))
            {
                <tr>
                    <td scope="row">
                        @i.YearOfWining
                    </td>
                    <td>
                        @i.Name
                    </td>
                    <td>
                        @i.ForWhat
                    </td>
                    <td>
                        <a href="/Personas/Details/@i.Persona.ID">
                            @i.Persona.FirstName
                            @i.Persona.LastName
                        </a>
                    </td>
                </tr>
            }
        </table>
        @if (Request.IsAuthenticated)
        {
            <a href="/Awards/CreateFAward/?idf=@Model.Film.ID">Dodaj nagrodę</a>

        }

        <br />
        <br />

        <h3>Obsada</h3>

        <table class="table" style="width: 50%">
            <tr>
                <th scope="col"></th>
                <th scope="col">Osoba</th>
                <th scope="col">Rola w filmie</th>
            </tr>

            @foreach (var i in Model.ListOfPersona)
            {

                <tr>
                    <td scope="row">
                        <img src="~/Images/p_@(i.ID).jpg" style="width:100px;height:120px;" href="/Personas/Details/@(i.ID)" class="img-fluid " />
                    </td>
                    <td>
                        <a href="/Personas/Details/@i.ID">
                            @i.FirstName
                            @i.LastName
                        </a>

                    </td>
                    <td>
                        @i.ListOfFilms.Where(x => x.Film == Model.Film).Single().Function
                    </td>

                </tr>

            }

        </table>
        @if (Request.IsAuthenticated)
        {
            <a href="/FilmHasPersonas/CreateF/?idf=@Model.Film.ID">Dodaj osobę</a>
        }

        <br />
        <br />



</div>

<p>
    
    @Html.ActionLink("Powrót do listy", "Index") | 

    @if (Request.IsAuthenticated)
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.Film.ID })
    }
    |
    @if (Context.User.IsInRole("Admin"))
    {
         @Html.ActionLink("Usuń z bazy", "Delete", new { id = Model.Film.ID }) 

    }
</p>

ProjektPZ/Views/Films/Edit.cshtml
@model ProjektPZ.Models.Film

@{
    ViewBag.Title = "Edytuj film";
    TempData["ID"] = Model.ID;
}

<h2>Edytuj film "@Model.Title"</h2>


@using (Html.BeginForm("Edit", "Films", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Tytuł filmu
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tytuł oryginalny
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrgTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrgTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Rok premiery
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfPremiere, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfPremiere, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Opis filmu
            <div>
                @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", @rows = 5, @cols = 60 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Dodaj plakat
            <div class="col-md-10">
                <input type="file" name="Image" />

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edytuj" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjektPZ/Views/Films/Index.cshtml
@model PagedList.IPagedList<ProjektPZ.Models.Film>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Lista filmów";
}

<h2>Lista filmów</h2>

<p>
        @if (Request.IsAuthenticated)
        {
            <h4>@Html.ActionLink("Dodaj nowy film", "Create")</h4>
        }

</p>
@using (Html.BeginForm())
{
    
        
    
    <p>
        Wyszukaj film: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        Gatunek:
        <select name="genre" id="genre">
            <option value="-1">Wszystkie</option>
            <option value="1">Dramat</option>
            <option value="2">Komedia</option>
            <option value="3">Triller</option>
            <option value="4">Horror</option>
            <option value="5">Dokumentalny</option>
            <option value="6">Obyczajowy</option>
            <option value="7">Gangsterski</option>
            <option value="8">Parodia</option>
            <option value="9">Kryminał</option>
            <option value="10" walki">Sztuki walki</option>
        </select>
        <input type="submit" value="Wyszukaj" />
    </p>
}
<table class="table" style="width: 70%">
    <tr>
        <th></th>
        <th>
            @Html.ActionLink("Sortuj po tytule", "Index", new { sortOrder = ViewBag.NameSortPackParam, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Gatunek filmu:
        </th>
        <th>
            @Html.ActionLink("Sortuj po roku premiery", "Index", new { sortOrder = ViewBag.DatePackParam, currentFilter = ViewBag.CurrentFilter })

        </th>
        <th></th>
    </tr>

        @foreach (var item in Model)
        {
            <tr onclick="location.href = '@(Url.Action("Details", "Films", new { id = item.ID }))'">

                <td>
                    <img src="~/Images/f_@(item.ID).jpg" style="width:100px;height:120px;" href="/Films/Details/@item.ID" class="img-fluid " />
                </td>
                <td>
                    <a href="/Films/Details/@item.ID">
                        <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
                        @if (!item.Title.Equals(item.OrgTitle))
                        {
                            <h3>@Html.DisplayFor(modelItem => item.OrgTitle)</h3>
                        }
                    </a>
                </td>
                <td>
                    @item.Genre.Name
                </td>
                <td> <p>
                        @item.YearOfPremiere
                    </p>
                    <p>
                        @{ 
                            int suma = 0;
                            int liczbaGlosow = item.Ratings.Count();
                            if (liczbaGlosow > 0)
                            {
                                foreach (var i in item.Ratings)
                                {
                                    suma += i.Rate;
                                }
                                suma /= liczbaGlosow;
                            }


                        }
                        <h4>Ocena: @(suma/10.0) </h4> <h5>Głosy: @liczbaGlosow </h5>
                    </p>    
                </td>
                <td>
                    @if (Request.IsAuthenticated)
                {
                        @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }) <br />

                    }
                    @if (User.IsInRole("Admin"))
                {
                        @Html.ActionLink("Usuń", "Delete", new { id = item.ID })
                    }

                </td>
            </tr>
        }
        @if (Model.Count == 0)
        {
            <tr><td><h3>Nie ma filmu</h3></td></tr>
        }
    </table>
<br />
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))